moneypenny:
  host: "data-dev.lsst.eu"

  ingress:
    enabled: true
    hosts:
      - host: data-dev.lsst.eu
        paths: ["/moneypenny"]
    annotations:
      nginx.ingress.kubernetes.io/auth-url: "https://data-dev.lsst.eu/auth?scope=exec:admin"

  vault_secrets:
    enabled: true
    path: "secret/k8s_operator/rsp-lapp/pull-secret"

  orders: |
    commission:
      - name: farthing
        image: lsstsqre/farthing
        securityContext:
          runAsUser: 1000
          runAsNonRootUser: true
          allowPrivilegeEscalation: false
    retire:
      - name: farthing
        image: lsstsqre/farthing
        securityContext:
          runAsUser: 1000
          runAsNonRootUser: true
          allowPrivilegeEscalation: false
