moneypenny:
  host: "data-dev.lsst.eu"

  ingress:
    enabled: true
    hosts:
      - host: data-dev.lsst.eu
        paths: ["/moneypenny"]
    annotations:
      nginx.ingress.kubernetes.io/auth-url: "https://data-dev.lsst.eu/auth?scope=admin:provision"

  vault_secrets:
    enabled: true
    path: "secret/k8s_operator/rsp-cc/pull-secret"

  orders: |
    commission:
      - name: initcommission
        image: lsstsqre/inituserhome
        securityContext:
          runAsUser: 0
          runAsNonRootUser: false
        volumeMounts:
        - name: home
          mountPath: /home
    retire:
      - name: farthing
        image: lsstsqre/farthing
        securityContext:
          runAsUser: 1000
          runAsNonRootUser: true
          allowPrivilegeEscalation: false
    volumes:
      - name: home
        hostPath:
          path: /data/rsp/home
          type: Directory
