environment: ccin2p3dev
fqdn: data-dev.lsst.eu
vault_path_prefix: secret/k8s_operator/rsp-cc

argo:
  enabled: true
cachemachine:
  enabled: true
cert_issuer:
  enabled: false
cert_manager:
  enabled: false
chronograf:
  enabled: false
exposurelog:
  enabled: false
gafaelfawr:
  enabled: true
influxdb:
  enabled: false
kapacitor:
  enabled: false
squareone:
  enabled: true
logging:
  enabled: false
mobu:
  enabled: false
moneypenny:
  enabled: true
ingress_nginx:
  enabled: true
nublado2:
  enabled: true
obstap:
  enabled: true
portal:
  enabled: true
postgres:
  enabled: true
rancher_external_ip_webhook:
  enabled: false
squash_api:
  enabled: false
tap:
  enabled: true
tap_schema:
  enabled: true
vault_secrets_operator:
  enabled: true
