gafaelfawr:
  imagePullSecrets:
    - name: "pull-secret"
  ingress:
    host: data-dev.lsst.eu
  vaultSecretsPath: "secret/k8s_operator/rsp-cc/gafaelfawr"

  redis:
    persistence:
      enabled: false

  config:
    host: "data-dev.lsst.eu"
    databaseUrl: "postgresql://gafaelfawr@postgres.postgres/gafaelfawr"

  # Do not specify ingress.host because we're using the wildcard virtual host.

  # Session length and token expiration (in minutes).
    issuer:
      exp_minutes: 43200  # 30 days

    github:
      clientId: ae314e45a6af43ea910a

  # Allow access by GitHub team.
    groupMapping:
      "admin:provision":
        - "in2p3-dp0-admin"
      "exec:admin":
        - "in2p3-dp0-admin"
      "exec:notebook":
        - "in2p3-dp0-admin"
        - "in2p3-dp0-user"
      "exec:portal":
        - "in2p3-dp0-admin"
        - "in2p3-dp0-user"
      "read:tap":
        - "in2p3-dp0-admin"
        - "in2p3-dp0-user"

    initialAdmins:
      - "bgounon"

pull-secret:
  enabled: true
  path: secret/k8s_operator/rsp-cc/pull-secret
