ingress-nginx:
  controller:
    nodeSelector:
      kubernetes.io/hostname: "ccqserv202"
    
    tolerations:
    - key: "dedicated"
      operator: "Equal"
      value: "qserv"
      effect: "NoSchedule"

    config:
      compute-full-forwarded-for: "true"
      large-client-header-buffers: "4 64k"
      proxy-body-size: "100m"
      proxy-buffer-size: "64k"
      ssl-redirect: "true"
      use-forwarded-headers: "true"
    service:
      externalTrafficPolicy: Local
      loadBalancerIP: "134.158.237.2"
    admissionWebhooks:
      enabled: false
    extraArgs:
      default-ssl-certificate: ingress-nginx/ingress-certificate
    podLabels:
      hub.jupyter.org/network-access-proxy-http: "true"

vault_certificate:
  enabled: true
  path: secret/k8s_operator/rsp-cc/ingress-nginx

pull-secret:
  enabled: true
  path: secret/k8s_operator/rsp-cc/pull-secret
