vault-secrets-operator:
  environmentVars:
    - name: http_proxy
      value: http://ccqserv201.in2p3.fr:3128
    - name: https_proxy
      value: http://ccqserv201.in2p3.fr:3128
    - name: VAULT_TOKEN
      valueFrom:
        secretKeyRef:
          name: vault-secrets-operator
          key: VAULT_TOKEN
    - name: VAULT_TOKEN_LEASE_DURATION
      valueFrom:
        secretKeyRef:
          name: vault-secrets-operator
          key: VAULT_TOKEN_LEASE_DURATION
  vault:
    address: "https://vault.lsst.codes"
